### ISSUE TITLE
Experiment hangs on "Loading..." after AWS Deploy

### ISSUE THREAD

**Issue by parkerrobbins** [pushkin-consortium/pushkin#148]
AWS Deploy was successful. When I click on my experiment, it hangs on "Loading..."

![image](https://user-images.githubusercontent.com/31826170/91346332-ae21d500-e7ae-11ea-98cc-26e43adb4ffb.png)

These are the errors (Chrome Version 85.0.4183.83):
1. Failed to load resource: net::ERR_CONNECTION_REFUSED  api.localhost/mind/startExperiment:1 
2. Uncaught (in promise) Error: Network Error
      at e.exports (createError.js:16)
      at XMLHttpRequest.d.onerror (xhr.js:83)

So because the first error says something about `localhost`, I'm guessing I didn't configure something correctly.

**Comment by jkhartshorne** [comment]
So the critical thing here is "api.localhost/mind/startExperiment:1". It should be "api.parkertrobbins.com/mind/startExperiment:1". So forwarding for your api isn't working correctly. 

Go to route 53 and open your hosted zone. Send me a screenshot of what you see. It should look a lot like this one:

![Screen Shot 2020-08-26 at 3 43 52 PM](https://user-images.githubusercontent.com/6118115/91349211-fe9b3180-e7b2-11ea-9fba-cc20f6e7090e.png)

**Comment by parkerrobbins** [comment]
@jkhartshorne (Also ignore the message about a commit referencing this issue; that was a mistake.)
![image](https://user-images.githubusercontent.com/31826170/91350817-3b682800-e7b5-11ea-89db-a27f4b6460c9.png)

**Comment by jkhartshorne** [comment]
@parkerrobbins  - you have to run 'prep' again after updating pushkin.yaml. I bet you didn't do that. I bet the instructions don't tell you to, either. I'll go update.

**Comment by jkhartshorne** [comment]
Oh, actually, you never enter it into pushkin.yaml yourself. So I think I understand what's going on and how to fix it. I'll let you know.

**Comment by jkhartshorne** [comment]
Should be fixed in cli v2.1.1

**Comment by restmegan** [comment]
I'm still having this issue with cli v.2.2.7, same errors in developer tools and very similar route 53 hosted zone records

**Comment by jkhartshorne** [comment]
Glad you got that far! Looks like the issue is with how the debug environment variable was being set up. This *should* be solved in v2.2.9. 

You don't need to rerun prep, but you'll probably need aws armageddon before running aws init.
